### ISSUE TITLE
Consider renaming this repository

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-quicktest-onboarding#1]
Hi 👋

I would suggest that you consider to rename this repository from `cwa-quicktest-oboarding` to `cwa-quick-test-onboarding` to match the naming of the [cwa-quick-test-frontend](https://github.com/corona-warn-app/cwa-quick-test-frontend) & [cwa-quick-test-backend](https://github.com/corona-warn-app/cwa-quick-test-backend) repository.

Please note that this should only be done if links to this repo weren't widely spread yet, since a renaming will break the old links.

**Comment by ilya-smirnov-berlin** [comment]
The URL was already distributed between several organisations.
