### ISSUE TITLE
Possbile inconsitency of test result encoding

### ISSUE THREAD

**Issue by dh3wr** [corona-warn-app/cwa-quicktest-onboarding#10]
## Describe the bug
There are different definitions how the rest result is encoded in numeric values:

https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-der-Partnersysteme#backend-integration:
![grafik](https://user-images.githubusercontent.com/16710361/119353257-f5d47f00-bca2-11eb-8cf6-5a738c6cc9b9.png)

vs.

https://github.com/corona-warn-app/cwa-testresult-server/blob/master/docs/architecture-overview.md#implemented-use-cases
![grafik](https://user-images.githubusercontent.com/16710361/119353342-0d136c80-bca3-11eb-80c8-4df43cb5f4de.png)

## Expected behaviour
Consitency of the docs, or I understood something wrong.

## Steps to reproduce the issue
Read the Docs :-)

**Comment by ilya-smirnov-berlin** [comment]
Original document / API is referring to PCR tests which use GUID while this area is for RAT tests. All test result values are correct.
