### ISSUE TITLE
Given urlbase64 encoded string takes JSON-dump with spaces

### ISSUE THREAD

**Issue by dh3wr** [corona-warn-app/cwa-quicktest-onboarding#11]
## Current Implementation
Der URL base64 encoded String nach https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-der-Partnersysteme#variante-mit-pers%C3%B6nlichen-daten ist aus folgendem JSON-Dump erzeugt:

``{ "fn": "Erika", "ln": "Mustermann", "dob": "1990-12-23", "timestamp": 1618386548, "testid": "52cddd8e-ff32-4478-af64-cb867cea1db5", "salt": "759F8FF3554F0E1BBF6EFF8DE298D9E9", "hash": "67a50cba5952bf4f6c7eca896c0030516ab2f228f157237712e52d66489d9960" }``

Zu senhen ist jeweils ein Space nach dem ersten ``{`` und vor dem letzten ``}``.

Übliche Implementationen zur JSON-Serialisierung bilden diesen allerdings nicht, z.B. in Pyhton ``json_data = json.dumps(jsonobj)``

Ergebnis:

``{"fn": "Erika", "ln": "Mustermann", "dob": "1990-12-23", "timestamp": 1618386548, "testid": "52cddd8e-ff32-4478-af64-cb867cea1db5", "salt": "759F8FF3554F0E1BBF6EFF8DE298D9E9", "hash": "67a50cba5952bf4f6c7eca896c0030516ab2f228f157237712e52d66489d9960"}``

## Suggested Enhancement
Dies liefert natürlich auch andere base64 Werte. Ich habe nun einige Zeit daran gesucht und würde Sie bitten,
1. Wenn die Spaces notwendig sind, dies zu erwähnen, oder
2. Ein Beispiel der verwendeten Serialisierung ebenfalls als String zu nennen, so dass man den Unterschied schneller findet.

Ggf. sind ja auch beide Varianten erlaubt, vielleicht weisen Sie aber dennoch darauf hin, dass einige Default-Libs wie z.B. in Python keine Leerzeichen ausgeben und daher der base64 Wert auch anders ist.

Vielen Dank

**Comment by vschi** [comment]
Ist es denn zwingend Notwendig dieses erwähnte Leerzeichen am Anfang und Ende zu erhalten oder nicht?
Ich habe das exakt gleiche Problem. Aber die Beispiele im Wiki zielen nur auf PHP Implementierungen und nicht auf Python.

**Comment by dh3wr** [comment]
Nein, es ist nicht notwendig. Ich hätte mich nur über einen Hinweis gefreut, dass python z.B. die Leerzeichen nicht erzeugt und daher der base64-Wert unterschiedlich ist. Ich habe ja zunächst das Beispiel nachprogrammiert und mich doch ein paar Minuten gewundert, warum der base64 Wert ein anderer ist in python als im angegebenen Beispiel.

**Comment by ilya-smirnov-berlin** [comment]
Leerzeichen spielen keine Rolle.
