### ISSUE TITLE
wiki: fix typo

### ISSUE THREAD

**Issue by janhoffmann** [corona-warn-app/cwa-quicktest-onboarding#12]
## Current Implementation

on:
https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/FAQ#warum-f%C3%BChrt-ein-app-link-nicht-zur-cwa-sondern-zum-browser--app-store--google-play

is a typo:
nicht zur CWA kommt, sondern **aud** die Seite https://s.coronawarn.app oder zum Ap

## Suggested Enhancement

fix the typo

**Comment by ilya-smirnov-berlin** [comment]
Fixed
