### ISSUE TITLE
Wiki in parts outdated?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-quicktest-onboarding#13]
## Your Question

* Source File: https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/CWA-Schnelltest-Portal
* Line(s): https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/CWA-Schnelltest-Portal#vertragsabschluss
* Question: Is the text still true? Are the forms still WIP? See the sentence: 
"Der erste Schritt ist die Unterzeichnung eines Nutzungsvertrages. Die notwendigen Formulare für den Vertragsabschluss sind in aktuell noch in Erstellung und können in Kürze angefragt werden."

**Comment by ilya-smirnov-berlin** [comment]
Text fixed. Schnelltest Portal is ready to use.
