### ISSUE TITLE
Mention contact e-mail address in Wiki

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-quicktest-onboarding#14]
## Current Implementation

https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki Does not mention the e-mail address.
 
## Suggested Enhancement

Mention your e-mail address there.

## Expected Benefits

Potential customers will have it easier to contact you if they have questions, etc.

**Comment by ilya-smirnov-berlin** [comment]
Fixed
