### ISSUE TITLE
What will be the influence of the decision to make it mandatory for rapid test centers to connect to the Corona-Warn-App?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-quicktest-onboarding#15]
## Your Question
* Source: https://twitter.com/phoenix_de/status/1399698359066284039?s=20
* Question: 
The Federal Minister of Health announced in the "Bundespressekonferenz" today: "[…] dass alle Teststellen die abrechnen können wollen nach der Verordnung an die Corona-Warn-App digital sich anschließen müssen.". 
What will be the influence of this decision on the onboarding process for new quick test partners? 
Will the onboarding be more easy? Or what's the plan to handle so many requests?

**Comment by Ein-Tim** [comment]
On the 01.08.2021 all test centers have to be connected to the quick test portal (or have send out a request to register) to be able to continue to get paid for the tests. 
On Twitter I now see the first people complaining that it takes too long and that they don't get a respond... 

Could we get an update here?

**Comment by ilya-smirnov-berlin** [comment]
https://www.kbv.de/html/1150_53277.php
