### ISSUE TITLE
Documentation of results codes is different

### ISSUE THREAD

**Issue by dh3wr** [corona-warn-app/cwa-quicktest-onboarding#17]
## Describe the bug
https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-der-Partnersysteme#backend-integration defines result status ``6-8``,

but 

https://github.com/corona-warn-app/cwa-quicktest-onboarding/blob/master/api/quicktest-openapi.json has a range of ``5-8`` with 5 being ``pending``.

## Expected behaviour
To have the same information at both places.

## Steps to reproduce the issue
Read the files on github.

**Comment by Ein-Tim** [comment]
Related to: #3

**Comment by ilya-smirnov-berlin** [comment]
Commented on this value.
