### ISSUE TITLE
Authentifizierung in PHP

### ISSUE THREAD

**Issue by curato2** [corona-warn-app/cwa-quicktest-onboarding#19]
Wie kann man in PHP das Testergebnis versenden und sich mit dem bereitgestellten Key zertifizieren? gibt es hierfür eine Anleitung (Dokumentation) und ein Programmierbeispiel für PHP ?

**Comment by curato2** [comment]
Wir haben es in PHP mit einem curl POST Request gelöst damit funktioniert die Weitergabe wunderbar - das ist die einfachste Implementierung gewesen, das mitgelieferte Package aus der openAPI.json ist unvollständig und für uns unbrauchbar...

`if($status=="negativ"){
    $result = 6;
}
elseif($status=="positiv"){
    $result = 7;
}
else{
    $result = 8;
}

$array=array();
$array["testResults"]=array();
$array["testResults"][]=array("id"=>$warnapp_hash,"result"=>$result);
$payload = json_encode($array);

$url = "https://quicktest-result-cff4f7147260.coronawarn.app/api/v1/quicktest/results";
$cert = "xxx.pem";
$certkey="xxx.key";

//open connection
$ch = curl_init();

//set options
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-type: application/json"));
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSLCERT, $cert);
curl_setopt($ch, CURLOPT_SSLKEY, $certkey);
curl_setopt($ch, CURLOPT_SSLCERTPASSWD, '');
curl_setopt($ch, CURLOPT_SSLKEYPASSWD, 'xxx');
curl_setopt ($ch, CURLOPT_VERBOSE , 0);

//execute post
curl_exec($ch);

//close connection
curl_close($ch);`

**Comment by arslandixeam** [comment]
hello,
i am using the given request in php, but i am getting 400 error.
```
<?php

$url = "https://quicktest-result-cff4f7147260.coronawarn.app?v=1#eyAiZm4iOiAiRXJpa2EiLCAibG4iOiAiTXVzdGVybWFubiIsICJkb2IiOiAiMTk5MC0xMi0yMyIsICJ0aW1lc3RhbXAiOiAxNjE4Mzg2NTQ4LCAidGVzdGlkIjogIjUyY2RkZDhlLWZmMzItNDQ3OC1hZjY0LWNiODY3Y2VhMWRiNSIsICJzYWx0IjogIjc1OUY4RkYzNTU0RjBFMUJCRjZFRkY4REUyOThEOUU5IiwgImhhc2giOiAiNjdhNTBjYmE1OTUyYmY0ZjZjN2VjYTg5NmMwMDMwNTE2YWIyZjIyOGYxNTcyMzc3MTJlNTJkNjY0ODlkOTk2MCIgfQ";
$cert = __DIR__ ."/output.crt";
$certkey= __DIR__ .'/ctc-wru.key';

//open connection
$ch = curl_init();

//set options
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-type: application/json"));
curl_setopt($ch, CURLOPT_URL, $url);
// curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSLCERT, $cert);
curl_setopt($ch, CURLOPT_SSLKEY, $certkey);
curl_setopt($ch, CURLOPT_SSLCERTPASSWD, '');
curl_setopt($ch, CURLOPT_SSLKEYPASSWD, 'xxxxxx');
curl_setopt ($ch, CURLOPT_VERBOSE , 0);

//execute post
$result = curl_exec($ch);
if (curl_errno($ch)) {
    $error_msg = curl_error($ch);
}
//close connection
curl_close($ch);
print_r($error_msg);
echo '<br>';
print_r($result);exit;
```

Here is my code.
output.crt file is provided by the cornawarn-app server.
ctc-wru.key is the generated by ubuntu (as mentioned in the wiki) (Link : https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-der-Partnersysteme)

Can anybody tell me where i am making mistake.
Thanks.

**Comment by arslandixeam** [comment]
@curato2  can u plz help me.
Thanks
