### ISSUE TITLE
PHP curl 403 Forbidden 

### ISSUE THREAD

**Issue by Janendran** [corona-warn-app/cwa-quicktest-onboarding#23]
Im trying to send the result api request and im getting 403 forbidden error. 

<img width="1310" alt="Screenshot 2021-07-06 at 16 44 27" src="https://user-images.githubusercontent.com/14290108/124591032-71684500-de79-11eb-8485-55d30be7c580.png">

               $result = 6;
                $array=array();
                $array["testResults"]=array();
                $array["testResults"][]=array("id"=>$hash,"result"=>$result);
                $payload = json_encode($array);

                $url = "https://quicktest-result-cff4f7147260.coronawarn.app/api/v1/quicktest/results";
                $cert = getcwd() . "/something.cer";
                $certkey= getcwd() . "/semething-wru.key";

                //open connection
                $ch = curl_init();
               
                //set options
                curl_setopt($ch, CURLOPT_HEADER, true);
                curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-type: application/json"));
                curl_setopt($ch, CURLOPT_URL, $url);
                curl_setopt($ch, CURLOPT_USERAGENT, 'User-Agent: curl/7.39.0');
                curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                curl_setopt($ch, CURLOPT_SSLCERT, $cert);
                curl_setopt($ch, CURLOPT_SSLKEY, $certkey);
                curl_setopt($ch, CURLOPT_SSLCERTPASSWD, '');
                curl_setopt($ch, CURLOPT_SSLKEYPASSWD, 'ticketbird');
                curl_setopt ($ch, CURLOPT_VERBOSE , 0);

                //execute post
                $response = curl_exec($ch);

                $info =curl_errno($ch)>0 ? array("curl_error_".curl_errno($ch)=>curl_error($ch)) : curl_getinfo($ch);
                echo "<br>";
                echo "<br>";
                print_r($info);
                //close connection
                curl_close($ch);

                echo $response;

**Comment by fjusufi-ubt** [comment]
I think here $array["testResults"][]=array("id"=>$hash,"result"=>$result); you're missing the sc, as per the instructions:

{
    "testResults":
    [
        {
            "id": "67a50cba5952bf4f6c7eca896c0030516ab2f228f157237712e52d66489d9960",
            "result": 6
            "sc" : 1625125748
        }
    ]
}

**Comment by ilya-smirnov-berlin** [comment]
Please try solution suggested here
https://github.com/corona-warn-app/cwa-quicktest-onboarding/issues/26#issuecomment-881297552

**Comment by marcbln** [comment]
I have the same problem, tried the example code in python (labsimulator.py), php version (test_dcc.php) and CLI version as well 
```bash
# test server 1
echo '{"labId": "someuniqlabid8675789087"}' | http --cert=test2.pem --ssl=tls1.2 POST https://dcc-proxy-cff4f7147260.coronawarn.app/version/v1/labId 'X-CWA-PARTNER-ID:AXXXX'
# test server 2
echo '{"labId": "someuniqlabid8675789087"}' | http --cert=test2.pem --ssl=tls1.2  POST https://quicktest-result-cff4f7147260.coronawarn.app/version/v1/labId 'X-CWA-PARTNER-ID:AXXXX'
```
all fails with 403 ..
