### ISSUE TITLE
400 ssl error on curl request (php)

### ISSUE THREAD

**Issue by arslandixeam** [corona-warn-app/cwa-quicktest-onboarding#26]
hello,
i am using the given request in php, but i am getting 400 error.

```
<?php

$url = "https://quicktest-result-cff4f7147260.coronawarn.app?v=1#eyAiZm4iOiAiRXJpa2EiLCAibG4iOiAiTXVzdGVybWFubiIsICJkb2IiOiAiMTk5MC0xMi0yMyIsICJ0aW1lc3RhbXAiOiAxNjE4Mzg2NTQ4LCAidGVzdGlkIjogIjUyY2RkZDhlLWZmMzItNDQ3OC1hZjY0LWNiODY3Y2VhMWRiNSIsICJzYWx0IjogIjc1OUY4RkYzNTU0RjBFMUJCRjZFRkY4REUyOThEOUU5IiwgImhhc2giOiAiNjdhNTBjYmE1OTUyYmY0ZjZjN2VjYTg5NmMwMDMwNTE2YWIyZjIyOGYxNTcyMzc3MTJlNTJkNjY0ODlkOTk2MCIgfQ";
$cert = __DIR__ ."/output.crt";
$certkey= __DIR__ .'/ctc-wru.key';

//open connection
$ch = curl_init();

//set options
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-type: application/json"));
curl_setopt($ch, CURLOPT_URL, $url);
// curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSLCERT, $cert);
curl_setopt($ch, CURLOPT_SSLKEY, $certkey);
curl_setopt($ch, CURLOPT_SSLCERTPASSWD, '');
curl_setopt($ch, CURLOPT_SSLKEYPASSWD, 'xxxxxx');
curl_setopt ($ch, CURLOPT_VERBOSE , 0);

//execute post
$result = curl_exec($ch);
if (curl_errno($ch)) {
    $error_msg = curl_error($ch);
}
//close connection
curl_close($ch);
print_r($error_msg);
echo '<br>';
print_r($result);exit;
```
Here is my code.
output.crt file is provided by the cornawarn-app server.
ctc-wru.key is the generated by ubuntu (as mentioned in the wiki) (Link : https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-der-Partnersysteme)

Can anybody tell me where i am making mistake.
Thanks.

**Comment by vaubaehn** [comment]
Hi @arslandixeam ,
I see a chance that your issue is related to https://github.com/corona-warn-app/cwa-quicktest-onboarding/issues/25.
Can you check if it works when you change your `$url` accordingly (add '/' after 'quicktest-result-cff4f7147260.coronawarn.app')?
As the SSL error would be the first before all other data are processed, I think it's because the whole `$url` is taken into account for SSL connection negotiation instead of 'only' `quicktest-result-cff4f7147260.coronawarn.app` .

Did this help? Short feedback appreciated.

**Comment by arslandixeam** [comment]
@vaubaehn i have changed $url from 

`https://quicktest-result-cff4f7147260.coronawarn.app?v=1#eyAiZm4iOiAiRXJpa2EiLCAibG4iOiAiTXVzdGVybWFubiIsICJkb2IiOiAiMTk5MC0xMi0yMyIsICJ0aW1lc3RhbXAiOiAxNjE4Mzg2NTQ4LCAidGVzdGlkIjogIjUyY2RkZDhlLWZmMzItNDQ3OC1hZjY0LWNiODY3Y2VhMWRiNSIsICJzYWx0IjogIjc1OUY4RkYzNTU0RjBFMUJCRjZFRkY4REUyOThEOUU5IiwgImhhc2giOiAiNjdhNTBjYmE1OTUyYmY0ZjZjN2VjYTg5NmMwMDMwNTE2YWIyZjIyOGYxNTcyMzc3MTJlNTJkNjY0ODlkOTk2MCIgfQ`

to
`https://quicktest-result-cff4f7147260.coronawarn.app/?v=1#eyAiZm4iOiAiRXJpa2EiLCAibG4iOiAiTXVzdGVybWFubiIsICJkb2IiOiAiMTk5MC0xMi0yMyIsICJ0aW1lc3RhbXAiOiAxNjE4Mzg2NTQ4LCAidGVzdGlkIjogIjUyY2RkZDhlLWZmMzItNDQ3OC1hZjY0LWNiODY3Y2VhMWRiNSIsICJzYWx0IjogIjc1OUY4RkYzNTU0RjBFMUJCRjZFRkY4REUyOThEOUU5IiwgImhhc2giOiAiNjdhNTBjYmE1OTUyYmY0ZjZjN2VjYTg5NmMwMDMwNTE2YWIyZjIyOGYxNTcyMzc3MTJlNTJkNjY0ODlkOTk2MCIgfQ`

but it still gives me same error. Any help would be appericiated.

**Comment by KDederichs** [comment]
Try adding 'CURLOPT_SSLVERSION' with 'CURL_SSLVERSION_TLSv1_2'

**Comment by ilya-smirnov-berlin** [comment]
Please check the PHP implementation at the code section.
