### ISSUE TITLE
When will the CWA Portal be finished and usable?

### ISSUE THREAD

**Issue by dg76** [corona-warn-app/cwa-quicktest-onboarding#31]
On https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/CWA-Schnelltest-Portal it says 

> "Der erste Schritt ist die Unterzeichnung eines Nutzungsvertrages. Die notwendigen Formulare für den Vertragsabschluss sind in aktuell noch in Erstellung und können in Kürze angefragt werden."

It seems that starting from August 1st it is required to connect to the CWA. That's in about a week. We would like to use the CWA Portal for this purpose. When will it become available?

**Comment by Ein-Tim** [comment]
@dg76 I think this is an outdated statement, see #13.

**Comment by dg76** [comment]
@Ein-Tim sorry, I didn't see that. But given that no one responded to your question it might be useful to keep this question here to maybe get an answer? 🤔

**Comment by Ein-Tim** [comment]
@dg76 

Ye, please leave this issue open too.

**Comment by muzasa** [comment]
Ich sitze und drehe daumen.. "onboarding" seit 4 Wochen und warte auf keys usw. sitzt nochwer auf heißen Kohlen?

**Comment by MaxS1996** [comment]
> Ich sitze und drehe daumen.. "onboarding" seit 4 Wochen und warte auf keys usw. sitzt nochwer auf heißen Kohlen?

ich warte auf die Freischaltung des WRU Zertifikats für die DC Umgebung, aber vom Support bekomme ich nur die Vertragsunterlagen des Portals als Antwort und die Hotline sieht sich nicht zuständig

**Comment by muzasa** [comment]
genau das habe ich auch bekommen.. gestern erst. und meine Registrierung war bereits am 16.06.
Die Dame am Telefon meinte: "oh, da muss wohl ein Fehler passiert sein".. anscheinend bin ich nicht der einzige, der mit einem "tut uns leid" abgespeist wird..

**Comment by MaxS1996** [comment]
Mir wurde am Telefon gesagt, dass die Hotline nur für das Portal zuständig sei, nicht für das eigene Backend.
Die Onboarding-Adresse schickt nur immer wieder die Verträge für das Portal, inzwischen habe ich die 6 oder 7 mal.

Für den Nachweis der Anbindung unseres Backends an die CWA für die KV habe ich auch noch keine Lösung gefunden.

**Comment by ericzielonka** [comment]
Was meinst du damit?
"Für den Nachweis der Anbindung unseres Backends an die CWA für die KV habe ich auch noch keine Lösung gefunden."
@MaxS1996

**Comment by MaxS1996** [comment]
> Was meinst du damit?
> "Für den Nachweis der Anbindung unseres Backends an die CWA für die KV habe ich auch noch keine Lösung gefunden."
> @MaxS1996

Ich weiß nicht, ob das alle betrifft, es geht darum, dass ab dem 01.08 die CWA-Anbindung nachgewiesen werden muss, wenn die Tests weiter vergütet zu bekommen:
https://www.lakbb.de/erweitert/newsletter-verwaltung/newsletter/newsletter-942021-aktualisierung-dokumente-anbindung-an-corona-warn-app-modul-digitales-impfzertifikat/

**Comment by ericzielonka** [comment]
Achso.
Das regeln wir direkt an der Teststationen der jeweiligen Kunden.
Wir bieten es allen Kunden die es wollen.
Sollte eine Prüfung kommen, dann werden wir das dem Kunden auch schriftlich bestätigen.

**Comment by MaxS1996** [comment]
Wir sind Teststation und nutzen unser eigenes Portal, wir können uns das ja schlecht selbst bescheinigen... 😅
________________________________

**Comment by ericzielonka** [comment]
Achso.
Dann ist das doch kein Thema. Die Regelung sagt ja nur aus, dass ihr als Testzentrum dem Kunden die CWA Implementierung anbieten müsst. Mehr nicht. Baut halt einfach nen Haken für die Doku mit ein "Keine Nutzung erwünscht" und dann habt ihr das.

Wir sind 3. Anbieter für alle die wollen. Da läuft das ein wenig anders ab.

**Comment by MaxS1996** [comment]
nicht ganz, es geht um diesen Abschnitt:
"Wichtig: Die Anbindung der testenden Apotheken an die Corona-Warn-App ist ab dem 01.08.2021 gesetzlich erforderlich, um die Vergütung der Bürgertestung nach § 4a TestV zu erhalten."

Und von uns möchte die KV nun eine Nachweis über die Anbindung an die CWA

**Comment by ericzielonka** [comment]
Achso. Apotheken... Irgs. Und da reicht der Vertrag für die Anbindung als Nachweis nicht aus?

**Comment by ilya-smirnov-berlin** [comment]
Das Schnelltestportal ist online. Der Text für Vertragsabschluss ist angepasst.
