### ISSUE TITLE
DCC is valid in CWA but not in Verify ACC App

### ISSUE THREAD

**Issue by jona7o** [corona-warn-app/cwa-quicktest-onboarding#35]
## Your Question

Hi, i have a problem with WRU and i am not sure why this happens. We have integrated the CWA with DCC and i can add the certificate in the Testflight CWA, get the EU Certificate and i can also validate the QR Code for every country inside of the CWA. Everything looks pretty good. But when i now try to validate the same QR code with the mentioned dgca-verifier-app-android verify app i get "Verification failed" or "Signing Certificate is expired.". I am not sure why this happens? Testflight CWA Version is 2.6.0.

This DCC QR Code must be valid in WRU until tomorrow. If you add it to CWA Testflight it is fine. If you scan it with the verifier app it is not valid.
![qrcode](https://user-images.githubusercontent.com/8403631/127377290-e4fce294-8006-4fff-96d9-3325c591c57e.jpeg)

![IMG_8001](https://user-images.githubusercontent.com/8403631/127377829-25c03d9f-ad03-47b3-bdcc-fceea10b529f.PNG)

<img width="510" alt="Bildschirmfoto 2021-07-28 um 20 38 21" src="https://user-images.githubusercontent.com/8403631/127377806-7895326b-6ac0-45e2-b580-405f1f05625b.png">

**Comment by ilya-smirnov-berlin** [comment]
The issue was localized. We are waiting for certificate update on the signer side.

**Comment by vervallsweg** [comment]
Started working again for me a couple of hours ago.

**Comment by ilya-smirnov-berlin** [comment]
Retested. The issue was fixed.
