### ISSUE TITLE
Nonsense in wiki

### ISSUE THREAD

**Issue by dominik42** [corona-warn-app/cwa-quicktest-onboarding#36]
## Your Question
Der folgende Satz im Wiki macht keinen Sinn und sollte korrigiert werden:

> Für den Zugang zum DCC-Server benötigen keine neue Clientzertifikate zu erstellen.

[https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-an-CWA-mit-Verwendung-von-DCCs](https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-an-CWA-mit-Verwendung-von-DCCs)

**Comment by ericzielonka** [comment]
Moin.

Das ist nur teilweise korrekt.
Das aktuelle DCC Wiki ist (leider) so aufgebaut, dass es schon eine vollständige Implementierung der CWA ohne DCC gibt und dies "nur" dazu kommt. Und dafür ist tatsächlich kein neues Zertifikat nötig.

Vg

**Comment by Ein-Tim** [comment]
@ericzielonka Aber der Satz macht doch einfach (grammatikalisch) keinen Sinn, oder?

**Comment by dominik42** [comment]
Das denke ich auch, ich meinte die deutsche grammatikalische Form dieses Satzes.

**Comment by ericzielonka** [comment]
Achso.
Ja. Okay. Ich dachte du meinst inhaltlich.
Das komplette Wiki ist naja... Unschön.

**Comment by ilya-smirnov-berlin** [comment]
Fixed
