### ISSUE TITLE
HTTP status code after posting DCC

### ISSUE THREAD

**Issue by lafidi** [corona-warn-app/cwa-quicktest-onboarding#38]
Hello,
currently I am trying to implement the DCC functionality into my quick test application. When I post the DCC to                             `<URL>/version/v1/test/<testid>/dcc` I get _200_ as a status. What does that mean? According to the API description 200 can never be returned. Any clue?

Thanks

**Comment by tschiela** [comment]
We have exactly the same problem. We get 200 response with empty body

**Comment by lafidi** [comment]
Still open on my side. 

@ilya-smirnov-berlin can you help me? 
I really don't get where the 200 comes from.
CWA-Hash in WRU is: a9b5d26200786b48f5056782ddc61e5fda2fe4b0cd011f0ad19015ed3871cb0b
DCC-Hash in WRU is: 5a90f8b84feb386bfe039c2d7e801a63ab3fd55afe29760d8a84746896084385

**Comment by lafidi** [comment]
Okay, now I figured out that 200 seems to be the correct status code. However my implementation did not work because I used fake birthdays and the application seems to be to clever to check if the birthday is in an acceptable range
