### ISSUE TITLE
always get empty body

### ISSUE THREAD

**Issue by tschiela** [corona-warn-app/cwa-quicktest-onboarding#39]
The searchPublicKeys endpoint always returns a HTTP 200 with an empty body. No matter how many requests we make. Have anybody an idea what we are doing wrong?

**Comment by vschi** [comment]
According to this description this is correct:
https://github.com/corona-warn-app/cwa-quicktest-onboarding/blob/master/api/quicktest-openapi.json
Row 48 is returning 200

If you sending 1 result only the answer will be 200 without any further text as result.
If you are using the multi result way the return will be 204.
Strange but this is how it seems to be implemented.

**Comment by dh3wr** [comment]
See #74
