### ISSUE TITLE
Blemishes in Wiki

### ISSUE THREAD

**Issue by apmyp1990** [corona-warn-app/cwa-quicktest-onboarding#40]
## Current Implementation

1. The testid should be uuid type 4 with a max length of 35, but even the example testid contains 36 characters. (picture 1)
2. The result json object consists of 3 attributes, but in the text it says there are only two. (picture 2)

## Suggested Enhancement

1. correct the length in the description (35 -> 36)
2. The text should be corrected to say 3 attributes instead of two. 

## Expected Benefits

Correct wiki

![image](https://user-images.githubusercontent.com/20161590/127832594-4e0b7165-ea08-431c-af09-9f9b41d90703.png)
![image](https://user-images.githubusercontent.com/20161590/127832687-5144d8cb-b179-46f1-9fa7-80fd3e51446c.png)

**Comment by MartinKonrad** [comment]
Fixed
