### ISSUE TITLE
/api/v1/quicktest/result gives 500 error response

### ISSUE THREAD

**Issue by wearekolossum** [corona-warn-app/cwa-quicktest-onboarding#41]
Hey,

i added the quicktest upload to a system of a client of mine. Everything is working fine so far (as far as i can tell as i don't have a iOS device at hand to use the testversion of the CWA), i am getting a 204 response for the upload with

`https://quicktest-result-cff4f7147260.coronawarn.app/api/v1/quicktest/results`

But when i then try to check the test result with the endpoint

`https://quicktest-result-cff4f7147260.coronawarn.app/api/v1/quicktest/result`

with the payload

```
{
    "id": "<SHA-256 signature from the id value from the testResult object>"
}
```

i am getting a `500 Internal Server Error` response. As far as i understand the docs at

`https://github.com/corona-warn-app/cwa-quicktest-onboarding/blob/master/api/quicktest-openapi.json`

that endpoint should be giving the result of a test specified by ID in a JSON object. Or am i wrong? Trying with the ID from the wiki also gives a `500 Internal Server Error` response.

Thanks and take care
Florian

**Comment by MartinKonrad** [comment]
Please be aware, that you need to hash the Test ID once more using sha256 before you send it to the server. Then the server returns the result of the given Test ID.

**Comment by wearekolossum** [comment]
Hey @MartinKonrad, thanks a lot for the info - i thought the once done hashing was enough. Anyways, i handed over a testResult of 6, but when i now retrieve the result it says 5. I double-checked payloads etc. Any idea? Or should i open a new ticket for this? The TestID from the Result-JSON is d79e55fbf9a277d8d003ae85eb0b8db986a83ed966e4ab318bac7b43fe657739 .

Thanks and take care
Florian

**Comment by MartinKonrad** [comment]
Sorry no idea on that. I tested it on the WRU and it returned "6" when the testresult was set to "6" and "5" when it was set to "5". So everything working as expected on my side.

**Comment by wearekolossum** [comment]
Hey @MartinKonrad , strange, did you tested it with the /api/v1/quicktest/result endpoint (which gives me a 500 error again by the way) or some other way?

Thanks and take care
Florian

**Comment by wearekolossum** [comment]
@MartinKonrad , i added a new ticket for this - so this can be closed. Thanks.
