### ISSUE TITLE
CBOR in node.js

### ISSUE THREAD

**Issue by tschiela** [corona-warn-app/cwa-quicktest-onboarding#42]
Iam trying to convert the HCERT-Container (CBOR) to a byte string. But how should i handle the object key -260 in JavaScript. Its not valid JSON. And if iam wrapping the -260 in quotes i dont get the correct  byte string. Any ideas somebody?

**Comment by ilya-smirnov-berlin** [comment]
Maybe this particulatr implementation can be useful for you:
https://github.com/paroga/cbor-js

**Comment by ilya-smirnov-berlin** [comment]
Please close the issue if you could solve this.

**Comment by vaubaehn** [comment]
@tschiela and @ilya-smirnov-berlin 
paroga's cbor-js is not actively maintained for a long time, and left behind with unsolved issues.
Found this one here, that apparently is still alive and a revive of cbor-js:
https://github.com/aaronhuggins/cbor-redux

**Comment by tschiela** [comment]
they are enough libraries out there. The problem is they all require an object as source. And the object should have a key -260. That its not valid in JavaScript. I find another solution:

`
const hcertContainer =
    {
       1: "DE",
       4: 1622714400,
       6: 1622541600,
       '-260': {
         1: dccKernel
       }
    };

cbor.encode(hcertContainer).toString('hex').replace('642d323630', '390103')
`

Iam using "-260" and replace later in the hex string.
