### ISSUE TITLE
Partnersystem Anmeldung

### ISSUE THREAD

**Issue by muzasa** [corona-warn-app/cwa-quicktest-onboarding#44]
Hallo liebes Community,
Ein bekannter von mir und ich haben uns für die "Partnersystem" anmeldung registriert und haben den Zugang zum Schnelltestportal bekommen. Haben wir hier etwas übersehen? (hypotetische Frage...) 
Freundliche Grüsse

**Comment by ilya-smirnov-berlin** [comment]
Bitte, melden Sie sich unter cwa-schnelltest-onboarding@t-systems.com für die Anbindung Ihrer Software an die Corona-Warn-App.
Neben der Kontaktdaten benötigen wir von Ihnen folgende Information:
Vertrag 1: Sie sind selbst Betreiber und binden Ihre Schnellteststellen über die Schnittstelle an
Vertrag 2: Sie sind Softwareanbieter und arbeiten mit nur einem Betreiber zusammen
Vertrag 3: Sie sind Softwareanbieter und haben mehrere Betreiber als Partner, die über Ihre Schnittstelle angebunden werden

**Comment by muzasa** [comment]
Das habe ich am 22.06. bereits gemacht und auch bereits mitgeteilt, dass ich softwareanbieter bin. und penibel darauf hingewiesen und auch alle zertifikate von meinen Partnern hingeschickt, als antwort kam nach 6 Wochen der schnelltestzugang.
am 16.07. von meinem Kollegen eine Registririerungswunsch auf Partnersystem, auch hier der Zugang nur zum Schnelltestportal.
beide male Antwwort von 

Heinz-Jörg Müller mit dem Betreff: "V...... Vertrag Schnelltestportal_Corona-Warn-App"
so wie es scheint, bekommen wir die richtigen Zugänge, erst in Oktober, wenn sich wieder die Gesetze ändern. 
Ich möchte ja nur einen "ooh, wir haben einen Fehler gemacht... hier der richtige Vertrag " stat " registrieren Sie sich bitte ..@ hier"..
ich bin definitiv nicht der einzige,.. unter Kollegen wird es immer lauter..
