### ISSUE TITLE
Mailbox is full

### ISSUE THREAD

**Issue by jona7o** [corona-warn-app/cwa-quicktest-onboarding#47]
Hi, the mailbox of the given e-mail address is full. I am not able to send a mail with a monthly update.

cwa-schnelltest-onboarding@t-systems.com (cwa-schnelltest-onboarding@t-systems.com)
Das Postfach des Empfängers ist voll und kann zurzeit keine Nachrichten annehmen. Versuchen Sie zu einem späteren Zeitpunkt noch mal, Ihre Nachricht zu senden, oder wenden Sie sich direkt an den Empfänger.

**Comment by ilya-smirnov-berlin** [comment]
Solved.
