### ISSUE TITLE
Zertifikate immer noch nicht bekommen für die WRU Umgebung

### ISSUE THREAD

**Issue by brkoglu** [corona-warn-app/cwa-quicktest-onboarding#49]
## Your Question
Wie lange dauert es bis die Onboarding Kollegen die Zertifikate bereitstellen?

Sorry, korrigiert mich wenn ich falsch liege, aber nachdem wir die beiden CSR Dateien generiert haben und diese schicken, müssen wir doch auf die signierten Zertifikate von CWA warten oder? Oder gibt es irgendwo einen anderen Hebel wo man es antriggern kann? Integration ist auf unserer Seite soweit fertig warte nur noch auf die Zertifikate damit ich es gegen die WRU Server testen kann. Meine E-Mails an cwa-schnelltest-onboarding@t-systems.com werden glaube ich mittlerweile alle ignoriert, bekomme keine einzige Antwort. Habt ihr einen Ratschlag wo ich noch nachfragen kann? Habt ihr auch das selbe Problem?

Edit#1
Der Zugang für Testflight ist auch nicht angekommen... und dann bekommt man eine Mail, dass sich nur 1400 Teststellen registriert haben... 

* Source File:
* Line(s):
* Question:

**Comment by kdewi** [comment]
Das System muss noch abgenommen werden. Leider ist die t-systems (oder deren Subdienstleister) ziemlich überfordert.
