### ISSUE TITLE
Produktivschaltung

### ISSUE THREAD

**Issue by kdewi** [corona-warn-app/cwa-quicktest-onboarding#50]
Hallo,

unser System wurde am 29.07. abgenommen. Seitdem warten wir erfolglos auf die Installierung unseres Client Zertifikat auf dem Produktivsystem. 
Wir bekommen mit unseren Zertifikaten einen 403 Fehler beim Zugriff auf das Produktivsystem zurück.

Was können wir tun?

Hier unser Verlauf:

12.07.2021 Bitte zur Abnahme an cwa-schnelltest-onboarding@t-systems.com
20.07.2021 Durch Eskalation an Hr. M. haben wir schließlich Kontakt zu Jörg N. bekommen
22.07.2021 Nach mehrmaligen Versuchen haben wir Jörg N. erreicht und konnten einen Termin zur Abnahme für den 29.07.2021 vereinbaren.
29.07.2021 Erfolgreiche Abnahme durch Jörg N.
02.08.2021 Nachfrage bei Jörg N., da wir noch kein Zertifikat bekommen haben
04.08.2021 Rückfrage von Fr. S.: Hr. Roland P. denen wir unsere initiale CSR zugesendet hatten, ist nicht mehr im Team. Fr. S. hat daher bei uns erneut das CSR angefragt
05.08.2021 Zusendung des Client Zertifikates durch Lutz S. mit dem Hinweis, dass es 24 Stunden bis zur Freischaltung dauern kann
06.08.2021 Wir bekommen vom Produktivsystem immer noch eine 403 Meldung. Nachfrage bei Hr. Lutz S.
08.08.2021 Wir bekommen vom Produktivsystem immer noch eine 403 Meldung.  Nachfrage bei Hr. Lutz S.
11.08.2021 Anfrage bei Fr. S. Hier haben wir die Rückmeldung bekommen, dass Herr Lutz S. in Urlaub ist
12.08.2021 Anfrage von Fr. S., ob unser Zertifikat die richtige Seriennummer hat

...

Zwichendurch haben wir mehrmalige Nachfragen an cwa-schnelltest-onboarding@t-systems.com gesendet ohne eine Antwort zu bekommen.

**Comment by ilya-smirnov-berlin** [comment]
Ihre Anfrage wurde weitergeleitet.

**Comment by kdewi** [comment]
vielen dank. A1025 ist unsere Partner-Id, falls Ihnen das hilft.
