### ISSUE TITLE
Kein Zugriff mehr auf Schnelltestportal

### ISSUE THREAD

**Issue by rsiade** [corona-warn-app/cwa-quicktest-onboarding#51]
Hallo,

folgendes Problem. Im Adminbereich habe ich die Daten unseres Schnelltestportales eingetragen. Seit dem ist die URL nicht mehr zu erreichen. Der Support reagiert leider nicht unter der angegebenen Mail. Gibt es hier einen Mitarbeiter von T-Systems, der sich dem Problem annehmen kann?

Vielen Dank!
Schöne Grüße
Ralf

**Comment by vaubaehn** [comment]
Schon mal die Telefonnummer probiert, die hier angegeben ist?
![grafik](https://user-images.githubusercontent.com/68376758/129761711-ca3ce682-b158-471e-b63a-fbcccfc34ec5.png)

**Comment by rsiade** [comment]
Ja, der Mitarbeiter könnte da leider auch nicht helfen. Soll eine Mail schreiben an das onboarding.

**Comment by vaubaehn** [comment]
Oha... dann viel Erfolg!

**Comment by rsiade** [comment]
Danke dir

**Comment by rsiade** [comment]
Was ich gestern noch vergessen habe. Über die Hotline habe ich Erfahren, das wir zwar bekannt sind. Allerdings gibt es wohl einen neuen Link zur Produktivversion. Der neue Link wurde per Mail an alle verschickt, nur wohl an uns nicht.
