### ISSUE TITLE
Partnerlösung per Curl, ob korrekt

### ISSUE THREAD

**Issue by muzasa** [corona-warn-app/cwa-quicktest-onboarding#52]
Hallo Freunde des CWA's :)
Ich musste mir gezwungener Maßen einen Iphone bestellen für die Testumgebung aber diese kommt erst übermorgen an. trotzdem möchte ich am Projekt weiterarbeiten und habe mal ein PHP zum Testserver ausgeführt.

https://github.com/corona-warn-app/cwa-quicktest-onboarding/blob/master/src/quicktest_upload.php

als Antwort bekomme ich folgendes und frage mich, ob das so i.O. ist (habe bei IP's ein "X" nachgestellt):

Array
(
    [url] => https://quicktest-result-cff4f7147260.coronawarn.app/api/v1/quicktest/results
    [content_type] => 
    [http_code] => 204
    [header_size] => 366
    [request_size] => 158
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.132351
    [namelookup_time] => 0.000678
    [connect_time] => 0.014425
    [pretransfer_time] => 0.077597
    [size_upload] => 121
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 916
    [download_content_length] => 0
    [upload_content_length] => 121
    [starttransfer_time] => 0.077635
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 80.158.XX.XXX
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 192.168.XX.XXX
    [local_port] => 46XXX
    [http_version] => 3
    [protocol] => 2
    [ssl_verifyresult] => 0
    [scheme] => HTTPS
    [appconnect_time_us] => 77378
    [connect_time_us] => 14425
    [namelookup_time_us] => 678
    [pretransfer_time_us] => 77597
    [redirect_time_us] => 0
    [starttransfer_time_us] => 77635
    [total_time_us] => 132351
)

Vielen Dank schon mal für jeglichen Feedback

**Comment by marcbln** [comment]
http 204 bekomme ich auch vom Test-Results-Server, Deine Implementierung sollte korrekt funktionieren, denke ich.

**Comment by muzasa** [comment]
Danke vielmals. kann ja dann schonmal weitermachen.

Eine kleinigkeit, was ich noch nicht verstehe ist:
An meiner Software/Webapplikation sind weitere Testzentren angebunden. Und die Anlage "3_Anlage_5_Liste_Teststellen.xlsx" habe ich ausgefüllt und zurückgeschickt. 
Ich dokumentiere penibel wer wieviel testet aber muss ich das nur für mich dokumentieren oder muss ich das irgenwo noch mitteilen, welcher Test von wem kommt? Ich meine ist "POST"e gerade nur:
$cwa_res_json = '{
    "testResults":
    [
        {
            "id": "'.$cwa_hash_mit.'",
            "result": $result,
            "sc": '.$cwa_result_timestamp.'
        }
    ]
}
';

aber nirgendswo, welche Teststelle das ist (intern schon).

Herlichen Dank nochmal vielmals. Ich habe das Gefühl, dass ich hier weiterbringende Antworten bekomme als bei T-Systems Hotline..
