### ISSUE TITLE
Schnelltest Portal Fehlermeldung Code 500

### ISSUE THREAD

**Issue by jehleindustrie** [corona-warn-app/cwa-quicktest-onboarding#53]
Hallo zusammen,

nach der Datenerfassung müssen die Daten geprüft, der QR Code gescannt, under der Vorgang abgeschlossen werden.
Nach de, klick auf Vorgang abschließen erschein folgende Meldung:

<img width="488" alt="Bildschirmfoto 2021-08-18 um 18 25 04" src="https://user-images.githubusercontent.com/89152919/129935552-dd4ef301-d7ea-4d6a-993f-5686c8f5681a.png">

Es ist ein Fehler aufgetreten: Request failed with status code 500

Es können somit keine Testungen angelegt werden. Das bereits seit mehreren Stunden!

Wer kann helfen?

Lg MJ

**Comment by JohnFCreep** [comment]
Hey, bei uns war das gleiche Problem. Eigentlich sollte der Benutzer erstellt worden sein, allerdings sind die Berechtigungen nicht übernommen worden. Rufen Sie noch einmal die Benutzerverwaltung auf und verteilen Sie die Berechtigungen. Falls der Benutzer nicht erscheint versuchen Sie es noch einmal und falls es dann immernoch nicht geht versuchen Sie es mit einem anderen Benutzernamen. Viele sind schon vergeben (war bei uns Fehlercode 409). LG
