### ISSUE TITLE
QR-Code Scannen testflight mit Namentlichen Daten erzeugt fehler

### ISSUE THREAD

**Issue by muzasa** [corona-warn-app/cwa-quicktest-onboarding#55]
Hallo an alle,
bin erfolgreich in der Testumebung aktiv und möchte ich einen "Namentlichen" QR-Code über über IOS Kamera scannen steht da:
"FEHLER - Der QR-Code kann keinen Schnelltest zugeordnet werden. Bitte scannen Sie einen geeigneten QR-Code.".

Scanne ich den Code über CWA-DEV-APP steht:
"QR-code ist ungültig - Der QR-Code ist ungültig oder wurde bereits auf einem Smartphone registriert. .... usw"

Scanne ich den mit der Liveversion auf einem anderen Gerät (nicht testflight) funktioniert der Code..... und es steht Ihr testergebnis steht noch nicht bereit.. oder so.

Ich erwähne noch schnell, dass die Pseudo anmeldung hervorragend klappt in jeder Konstellation.. auch mit Ergebnissen auf Testflight.
Ich kann mir das nicht erklären.

Das Funktioniert bestens:
`$cwa_hash = strtolower (hash("sha256","$cwa_timestamp#$cwa_salt"));
$cwa_TE = '{"timestamp":'.$cwa_timestamp.',"salt":"'.$cwa_salt.'","hash":"'.$cwa_hash.'"}';`

Das erzeugt den Fehler:
`$cwa_hash = strtolower (hash("sha256","$cwa_timestamp#$cwa_salt"));
$cwa_TE = '{"timestamp":'.$cwa_timestamp.',"salt":"'.$cwa_salt.'","hash":"'.$cwa_hash.'"}';`

zu Testzwecken sieht mein  Code wie folgt aus:
`if($cwa == "cwaperso"){
// Perso								
$cwa_hash = strtolower (hash("sha256","$cwa_dob#$cwa_fn#$cwa_ln#$cwa_timestamp#$cwa_testid#$cwa_salt"));
$cwa_TE = '{"fn":"'.$cwa_fn.'","ln":"'.$cwa_ln.'","dob":"'.$cwa_dob.'","timestamp":'.$cwa_timestamp.',"testid":"'.$cwa_testid.'","salt":"'.$cwa_salt.'","hash":"'.$cwa_hash.'"}';
}else{
// Pseudo Daten
$cwa_hash = strtolower (hash("sha256","$cwa_timestamp#$cwa_salt"));
$cwa_TE = '{"timestamp":'.$cwa_timestamp.',"salt":"'.$cwa_salt.'","hash":"'.$cwa_hash.'"}';
}

#$cwa_url = strtr( base64_encode($cwa_TE), '+/=', '-_,' );
$cwa_url = base64_encode($cwa_TE);
$encode_mit_url = "https://s.coronawarn.app?v=1#$cwa_url";
QRcode::png($encode_mit_url, $tempDir.'cwa_'.$cwa_testid.'.png', QR_ECLEVEL_H, 5);
$cwa_qrcode = ''.$tempDir.'cwa_'.$cwa_testid.'.png';
`

**Comment by vaubaehn** [comment]
Hi, mir ist gerade das hier aufgefallen:
```
#$cwa_url = strtr( base64_encode($cwa_TE), '+/=', '-,' );
$cwa_url = base64_encode($cwa_TE);
```
Deeplink und QR-Code-Daten müssen mit base64url enkodiert werden, sonst kann es _manchmal_ zu Fehlern kommen, falls einige Zeichen mit '/' kodiert werden (base64url kodla et sie zu '_').

Das löst wahrscheinlich das Problem von oben nicht, ist aber trotzdem wichtig.

**Comment by vaubaehn** [comment]
Ein anderer Nutzer hatte berichtet, dass bei ihm auch nur bei personalisierten Daten ein Fehler auftrat. Hier war das Problem, dass die Hash-Funktion ein secret verwendete - das musste weggelassen werden. Das scheint hier aber auch nicht der Fall zu sein?
https://github.com/corona-warn-app/cwa-quicktest-onboarding/issues/30

**Comment by muzasa** [comment]
Vielen Dank für die Hilfestellung!
secret war nicht drin aber ich habe es jetzt geschafft, dass der Test aufgenommen wird. Es lag offensichtlich an der "Base64Url". Drumdessen habe ich diesen Schnippsel arbeiten lassen mit erfolg:

`function b64url_encode($a){
  $b = base64_encode($a);
  $url = strtr($b, '+/', '-_');
  return rtrim($url, '=');
}`

Allerdings, nachdem ich den Test aufnehme und ein Resultat schicke; passiert nichts.
Wiederum das gleiche System mit "nicht Namentlichen" funktioniert es.

ist es nicht so, dass ich ein und das selbe json Curl'e, ob Namentlich oder nicht Namentlich?

`$cwa_result = '{"testResults":[{"id":"'.$hash.'","result":'.$testResult.',"sc":'.$cwa_result_timestamp.'}]}';`

**Comment by vaubaehn** [comment]
Ich glaube, es wäre am einfachsten, wenn wir und mal für namentlich und nicht namentlich jeweils einen vollständig erzeugten deep link (https://s.coronawarn.app/?v=1#ey...) anschauen könnten.

**Comment by muzasa** [comment]
> 
> 
> Ich glaube, es wäre am einfachsten, wenn wir uns mal für namentlich und nicht namentlich jeweils einen vollständig erzeugten deep link (https://s.coronawarn.app/?v=1#ey...) anschauen könnten.

Namentlicher Link:
 https://s.coronawarn.app?v=1#eyJmbiI6IkVyaWthIiwibG4iOiJNdXN0cm1hbmduIiwiZG9iIjoiMjAwMC0wMi0wMSIsInRpbWVzdGFtcCI6IjE2Mjk3MTE0NjQiLCJ0ZXN0aWQiOiJURV8xNjI2MTc4OTEwLUJLQSIsInNhbHQiOiJEQ0NBNUVDQTZFRTgwQUQ0MjFBOTBBQzhGQTVFMzM0MiIsImhhc2giOiJmY2QwZDEzZjAxOWI0NGRhYWQwZDdiOTRmZGQ3M2VjMDVjMWJlN2JlZWUyYTZlNjI3NmUwOTFiY2M4MmQ2MDI1In0


Nicht Namentlicher:

https://s.coronawarn.app?v=1#eyJ0aW1lc3RhbXAiOjE2Mjk3MTE0NjQsInNhbHQiOiJEQ0NBNUVDQTZFRTgwQUQ0MjFBOTBBQzhGQTVFMzM0MiIsImhhc2giOiI0NGVhM2M3MTBkYTUxZWVjMzE5OTFhMDBhMmFkODkzZDE2ZGEwOTA4MDdiZWM4NzUyODMyMWQ5NzFjMjFhYTFlIn0

**Comment by vaubaehn** [comment]
Ok, das hilft.

Debugging namentlicher Link:
`{"fn":"Erika","ln":"Mustrmangn","dob":"2000-02-01","timestamp":"1629711464","testid":"TE_1626178910-BKA","salt":"DCCA5ECA6EE80AD421A90AC8FA5E3342","hash":"fcd0d13f019b44daad0d7b94fdd73ec05c1be7beee2a6e6276e091bcc82d6025"}`

Vom Format her ok: dob, fn, hash (Wert nicht überprüft), ln, salt, testid.

**Falsches Format:** timestamp => der Wert darf nicht in Anführungszeichen stehen (kein String, sondern integer). Siehe hier: https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-der-Partnersysteme-ohne-DCC#erstellung-von-qr-codes-f%C3%BCr-corona-warn-app
Richtig wäre also: `"timestamp":1629711464`

Debugging nicht namentlicher Link:
{"timestamp":1629711464,"salt":"DCCA5ECA6EE80AD421A90AC8FA5E3342","hash":"44ea3c710da51eec31991a00a2ad893d16da090807bec87528321d971c21aa1e"}

Hier scheint vom Format her alles zu stimmen (der timestamp ist auch integer).

Ich glaube, dann haben wir's.

**Comment by vaubaehn** [comment]
Wenn dann das Testergebnis an den Test-Result-Server gePOSTed wird, vielleicht vorsichtshalber auch nochmal drauf achten, dass der 'sc' timestamp und das Ergebnis 'result' auch integer sind (nicht strings). Nur die 'id' ist hier string.
Dann sollte eigentlich alles klappen...

**Comment by muzasa** [comment]
Kann es sein, dass der Zeitstempel identisch sein muss? im Moment habe ich einen Zeitstempel, wenn ich den Test anlege und curle zu einem späteren  Zeitpunkt den Befund.. Wenn ich nun den QR-Code und den Befund gleichzeitig generiere und schicke scheint es zu funktionieren. Generiere ich aber den QR-Code zuerst und sende den Befund im Anschluss -> wieder keine Reaktion und Befund in der CWA nicht sichtbar, bis auf, dass es angelegt wurde.

Danke nochmal vaubaehn! das mit "INT" mache ich gleich

**Comment by vaubaehn** [comment]
> das mit "INT" mache ich gleich

Vielleicht klappt es danach ja schon.

> Kann es sein, dass der Zeitstempel identisch sein muss?

Das sollte nicht so sein.

> im Moment habe ich einen Zeitstempel, wenn ich den Test anlege und curle zu einem späteren Zeitpunkt den Befund..

Meiner Meinung nach MUSS es sogar so sein, dass die Zeitstempel unterschiedlich sind - denn sonst wäre der Zeitpunkt, den die CWA für die Testdurchführung anzeigt, nicht korrekt, und die Zeitspanne für den Ablauf des Tests ebenfalls falsch.

Wenn das mit den unterschiedlichen Zeitstempeln nicht funktionieren sollte, hätten wir ein Problem...

**Comment by muzasa** [comment]
Problem gelöst. Ich weiss nicht wie, aber ich habe es in meine Live-Umgebung implementiert mit einem Testmandanten-Konto und es lief.. auf gehts WRU raus und live keys rein. Danke nochmal an alle.
PS: Zeitstempel geht mit unterschiedlichen, aber auch gleiche...

**Comment by vaubaehn** [comment]
@muzasa Schön, dass nun alles funktioniert. Dann kann das issue hier geschlossen werden?
Viel Erfolg weiterhin!
