### ISSUE TITLE
Error with sending result to test server

### ISSUE THREAD

**Issue by philharmonie** [corona-warn-app/cwa-quicktest-onboarding#57]
## Describe the bug

I copy and pasted the [example code](https://github.com/corona-warn-app/cwa-quicktest-onboarding/blob/master/src/quicktest_upload.php) to my app and I receive the following error message:

```
["curl_error_58"]=> string(109) "unable to set private key
file: '/Users/username/path/to/my/app/api/cert/MyCert-wru.key'
type PEM"`
```

the php example references the key as:
`@param $keyPath  - Path to your key file xxx-wru.key`
but from the error, I see, it expects a PEM type, so I renamed my file to PEM, as key is the same format as pem.

The error changes to:
```
["curl_error_58"]=> string(109) "unable to set private key
file: '/Users/username/path/to/my/app/api/cert/MyCert-wru.pem'
type PEM"`
```

I double checked the path and it is a valid path with a valid file.

I already came across https://github.com/corona-warn-app/cwa-quicktest-onboarding/issues/33 but it does not help.

## Expected behaviour

I expected to use a key file and the submission of my result. With the error message I expected the pen file to work as well.

## Steps to reproduce the issue

You should be able to reproduce the issue if you copy and paste the php example and run the `sendTestResult` function.

## Possible Fix

I'd suggest to fix the example to use a pem file instead of a key file.
Anyhow with each of these file I expect the example to work.

## Additional context

None

**Comment by philharmonie** [comment]
Got it fixed with:
```
openssl rsa -in MyCert-wru.key -text > MyCert.wru.pem
```

**Comment by Oe96** [comment]
Still got "unable to set private key file" after doing:

> Got it fixed with:
> 
> ```
> openssl rsa -in MyCert-wru.key -text > MyCert.wru.pem
> ```

Someone may can help?
