### ISSUE TITLE
Documentation enhancement for DCC onboarding

### ISSUE THREAD

**Issue by plaili** [corona-warn-app/cwa-quicktest-onboarding#58]
While implementing DCC I found same small enhancements, that could be made to the documentation.
It replaces tabs by spaces, correct some spelling errors, fixes duplicate variable name and a missing declaration in the Java implementation hint and adds some more detail to the QR code generation example.

**Comment by plaili** [comment]
[documentationEnhancements.txt](https://github.com/corona-warn-app/cwa-quicktest-onboarding/files/7128414/documentationEnhancements.txt)

**Comment by ilya-smirnov-berlin** [comment]
Thanks! Changes applied.
