### ISSUE TITLE
Wiki uses "Corona Warn App" without hyphens

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-quicktest-onboarding#6]
## Describe the bug

The wiki uses the term "Corona Warn App" without any hyphens, in these documents:

- https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-der-Partnersysteme
- https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Vertragsabschluss
- https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Checkliste-Abnahmetest
- https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/CWA-Schnelltest-Portal
- https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/FAQ

## Expected behaviour

Corna-Warn-App should be written with hyphen.

## Possible Fix

Write Corona-Warn-App with hyphen.

## Additional context

I'd like to fix this myself, in fact I even prepared it, but I can't edit wikis in any form, sorry. 
See #7

**Comment by DerVogel2020** [comment]
I just found the same typos and tried to provide a PR but it seems that the wiki cannot be forked.

**Comment by Ein-Tim** [comment]
@DerVogel2020 

No, you can't fork it.

**Comment by ilya-smirnov-berlin** [comment]
Replaced all occurrences of Corona Warn App with Corona-Warn-App.
