### ISSUE TITLE
What date is required for DCC (iat) and (exp)

### ISSUE THREAD

**Issue by VerHext** [corona-warn-app/cwa-quicktest-onboarding#60]
I am a bit confused about the dcc conversion and need some clarification here.

It is about the Issues At (iat) and Expiration Time (exp). In my opinion, this is the date of certificate creation. 
Anyway, in the [EU document](https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v1_en.pdf) the value iat is described as "indicating the time when the health certificate was created". 

Also, the [code example from Telekom itself](https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-an-CWA-mit-Verwendung-von-DCCs#programmatische-erzeugung-von-dcc-mit-dgc-lib) uses the date "now" here. The code in this function is only executed when a public key is available for encryption.

However, the Telekom employee in the acceptance test said that this is the date when the sample was taken. This means that we would have to issue certificates for the past. For me, this is difficult to understand. 
According to [rfc8392 3.1.6](https://datatracker.ietf.org/doc/html/rfc8392#section-3.1.6), iat is also described as the date of issue. 

If you use the issue date now, you would calculate the expiration date with iat + 2 days according to the[ GitHub doc](https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-an-CWA-mit-Verwendung-von-DCCs#dcc-datenstruktur). But this would mean that the certificate is valid longer than it should.

If one should take here two different times for 
iat = now
exp = time of test + 2 days 
the GitHub documentation is very incomprehensible, with the quantification of both dates under one name.

So please explain what exactly is means under the "Ausstellungsdatum" in the GitHub docu.

**Comment by plaili** [comment]
The thing here is that the iat is used to show the user the date when the sample was taken. So maybe it is kind of a misuse of iat but it has to be set to the date/time when the sample was taken. 
But yes it's very unfortunate that the Java example uses now()

**Comment by VerHext** [comment]
Thank you for the clarification and modification of the doc. Now the GitHub documentation is also consistent with the definition of the eu so I close this question.
