### ISSUE TITLE
Determination of public keys is not working well.

### ISSUE THREAD

**Issue by DeVeteranTeam** [corona-warn-app/cwa-quicktest-onboarding#63]
Hello everyone, hope you are doing well.
I tried to determine the public keys for existing results but DCC proxy service always respond with empty array: "[]".
I used the API - [Base-URL des DCC-Servers]/version/v1/publicKey/search/{labId} 
I made sure that my test results are registered on test result server using this API:[Base-URL des Test-Result-Servers]/api/v1/quicktest/result.

I checked this link https://github.com/corona-warn-app/cwa-quicktest-onboarding/tree/master/src/dcc_simulator_php and my script was equal to this in its functionality and flow.
I am not sure why it happens.
Who can help me with this?
Thanks for your reading.

**Comment by darshansheta** [comment]
@DeVeteranTeam  Did you find any solution?

**Comment by ilya-smirnov-berlin** [comment]
Please ensure QR-Code for RAT were scanned in CWA and DCC were enabled by user. Only after this you'll receive a key.
