### ISSUE TITLE
403 on https://dcc-proxy-cff4f7147260.coronawarn.app

### ISSUE THREAD

**Issue by feuergott** [corona-warn-app/cwa-quicktest-onboarding#66]
Hi everyone,

when calling /version/v1/publicKey/search/someLabID or /version/v1/someLabID on WRU DCC Server i get Status 403 as return. 
As far as I understand openAPI this errorcode has different reasons on those two called functions, so i assume 403 is returned as "general" error, no matter which function is called.

Searching my Public Keys worked fine for several days, no change was made to my code.

Is there a problem on WRU servers or is there a problem with my certificate?

Thanks in advance

**Comment by ilya-smirnov-berlin** [comment]
Please retest the access to the backend. We don't have any issues in WRU environment now.
