### ISSUE TITLE
Use Markdown files instead of Wiki

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-quicktest-onboarding#7]
## Current Implementation

All information is stored in the Wiki. It's not possible for community contributors to edit the content of it.

## Suggested Enhancement

Consider to use markdown files instead of GitHub Wikis.

## Expected Benefits

The community can edit the content of the Wiki.

**Comment by ilya-smirnov-berlin** [comment]
Rejected.
