### ISSUE TITLE
Cryptografic strong random bytes generation for DGC request

### ISSUE THREAD

**Issue by dh3wr** [corona-warn-app/cwa-quicktest-onboarding#79]
## Current Implementation
Python Code Starting line 40 [https://github.com/corona-warn-app/cwa-quicktest-onboarding/blob/master/src/testcenter_simulator/labsimulator.py](https://github.com/corona-warn-app/cwa-quicktest-onboarding/blob/master/src/testcenter_simulator/labsimulator.py)
````
def handle_dgc_request( self, testId, dcci, publicKeyStr ):
        "Erstellt eine Antwort auf einen DCC-Antrag"

        # Zufälligen Schlüssel erzeugen
        # (Achtung! Pseudo-Zufallszahlen! Dies ist nur zum Testen)
        dek = random_bytes(32)
````

## Suggested Enhancement

Use python lib ``secrets``
````
#dek = random_bytes(32)
dek = secrets.token_bytes(32)
````

## Expected Benefits
More secure encryption

**Comment by ilya-smirnov-berlin** [comment]
Fixed
