### ISSUE TITLE
create-client-csr.sh not working

### ISSUE THREAD

**Issue by elmorondo** [corona-warn-app/cwa-quicktest-onboarding#81]
When executing create-client-csr.sh the script gives me the following feedback:
```
: not foundient-csr.sh: 2:
: not foundient-csr.sh: 5:
Generating key for Teststation XY-prod
Extra arguments given.
genrsa: Use -help for summary.
Create signing request for Teststation XY-prod
req: Use -help for summary.
: not foundient-csr.sh: 10:
Generating key for Teststation XY-wru
Extra arguments given.
genrsa: Use -help for summary.
Create signing request for Teststation XY-wru
req: Use -help for summary.
: not foundient-csr.sh: 15:
ls: cannot access '*.csr'$'\r': No such file or directory@t-systems.com:
```
I think  openssl asks for a passphrase but i have none.

* Source File: create-client-csr.sh
* Line(s): 17,19,22,24
* Question: How can i make the script work?

**Comment by ilya-smirnov-berlin** [comment]
This script works under linux sh shell. Please don't use spaces in the name of your organisation.
Example: 
`./create-client-csr.sh teststation-xy`

**Comment by elmorondo** [comment]
> This script works under linux sh shell. Please don't use spaces in the name of your organisation. Example: `./create-client-csr.sh teststation-xy`

Thanks, it doesn't worked under Windows Subsystem for Linux. 

Executed the script on ubuntu and now it needs a passphrase to enter, is there a given passphrase or can i invent any passphrase? The quicktest-onboarding wasn't clear at this point.

**Comment by ilya-smirnov-berlin** [comment]
You can set the passphrase; you will need this passphrase for access to the qucktest result backend.

**Comment by elmorondo** [comment]
Thank you very much! Closed :)
