### ISSUE TITLE
cwa-schnelltest-onboarding@t-systems.com no reaction

### ISSUE THREAD

**Issue by celevra** [corona-warn-app/cwa-quicktest-onboarding#82]
sorry to use this Platform for this kind of problems, but i see no other way to contact the right person

we need to get access to the api for fasttests. We have written to cwa-schnelltest-onboarding@t-systems.com on the 5th januar, these are 20 Days now....
We need to get in prodaction with our app, it could not be that we have to wait that long to sign the contracts and get an api key....

how to proceed?

regards

Philipp Zeitschel

**Comment by daniel-eder** [comment]
@celevra Thank you for your message!

In your case the correct e-mail address to contact is cwa-onboarding-schnittstelle@t-systems.com, see also  https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki#option-2-cwa-schnittstellen-l%C3%B6sung for the information to include to ensure fast processing.

**Comment by celevra** [comment]
Thank your for your answer but we've sendet it also to the correct one and with the right subject




Von: Daniel Eder ***@***.***>
Gesendet: Montag, 24. Januar 2022 18:18
An: corona-warn-app/cwa-quicktest-onboarding
Cc: Philipp Zeitschel; Mention
Betreff: Re: [corona-warn-app/cwa-quicktest-onboarding] ***@***.*** no reaction (Issue #82)







@celevra Thank you for your message!
In your case the correct e-mail address to contact is 
***@***.***, see also 
https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki#option-2-cwa-schnittstellen-l%C3%B6sung for the information to include to ensure fast processing.
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
Triage notifications on the go with GitHub Mobile for 
iOS or 
Android. 
You are receiving this because you were mentioned.Message
 ID: ***@***.***>
