### ISSUE TITLE
Links at the bottom of the wiki do not work

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-quicktest-onboarding#86]
## Describe the bug

The links to www.coronawarn.app and map.schnelltestportal.de do not work. When clicked, a hint that one does not have the permission to update the wiki is shown.

https://user-images.githubusercontent.com/67682506/151550832-142a7375-0964-4b03-923f-9309463de4f9.mov

## Expected behaviour

The links should work.

## Steps to reproduce the issue

1. Open https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki
2. Scroll to the very bottom
3. Click on the link www.coronawarn.app
4. See that you only get the error that you are not allowed to edit the wiki but you are not redirect to the website

**Comment by ilya-smirnov-berlin** [comment]
Fixed
