### ISSUE TITLE
GUID not explicitly explained in Documentation

### ISSUE THREAD

**Issue by dh3wr** [corona-warn-app/cwa-quicktest-onboarding#9]
Unter [https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/FAQ#wie-ist-der-qr-code-aufgebaut-und-wird-die-cwa-guid-erzeugt](https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/FAQ#wie-ist-der-qr-code-aufgebaut-und-wird-die-cwa-guid-erzeugt) wird erwähnt, dass in der verlinkten Seite [https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-der-Partnersysteme#erstellung-von-qr-codes-f%C3%BCr-corona-warn-app](https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-der-Partnersysteme#erstellung-von-qr-codes-f%C3%BCr-corona-warn-app) erkärt wird, wie die GUID aufgebaut ist. Allerdings ist das Wort ``GUID`` nicht auf der Seite vorhanden.

### Frage: Was genau ist die GUID, welche wohl auch zur Übermittlung des Testergebnisses notwendig ist? Ist es der SHA256-Hash?

Vielen Dank

**Comment by ilya-smirnov-berlin** [comment]
Anstelle von GUID wird eine vom Testzentrum-Betreiber generierte interne ID verwendet. Das wird in der aktiuellen Anleitung erklärt. Die Frage wurde aus FAQ entfernt.
