### ISSUE TITLE
Testergebnis erfolgreich eingestellt, aber App sagt "Ergebnis liegt noch nicht vor"

### ISSUE THREAD

**Issue by WePo64** [corona-warn-app/cwa-quicktest-onboarding#90]
Ich verwende die Testapp über Testflight auf einem iPhone.

Problembeschreibung:
Das Testergebnis wurde erfolgreich mit der Api bereitgestellt (Result 204)
Bei der Testergebnisabfrage über die Api wird Result 200, TestResult 6 zurückgeliefert.
Der QR-Code kann problemlos in die Testflight-APP auf einem iPhone gescannt werden.
Die App zeigt an: "Ergebnis liegt noch nicht vor"

Was mache ich falsch?

Testdaten:

API-Url: https://quicktest-result-cff4f7147260.coronawarn.app

```
Timestamp: 1644945777
Salt: 4E2E223ED4F24DC787DEC5D75EB14F0F
```
```
HashString: 1644945777#4E2E223ED4F24DC787DEC5D75EB14F0F
HashValue: dee72da76ce437713fc4a3f7fd04693a74dac923f829ab7aec75e8acea8f2c41
```
```
Json:
{ "timestamp": 1644945777, "salt": "4E2E223ED4F24DC787DEC5D75EB14F0F", "hash": "dee72da76ce437713fc4a3f7fd04693a74dac923f829ab7aec75e8acea8f2c41" }
```
`JsonSha256: 891ea3d2cd72351af919b59ec428823507b67742addd08fd458ed01a3cf2aab2
`
Url: https://s.coronawarn.app/?v=1#eyAidGltZXN0YW1wIjogMTY0NDk0NTc3NywgInNhbHQiOiAiNEUyRTIyM0VENEYyNERDNzg3REVDNUQ3NUVCMTRGMEYiLCAiaGFzaCI6ICJkZWU3MmRhNzZjZTQzNzcxM2ZjNGEzZjdmZDA0NjkzYTc0ZGFjOTIzZjgyOWFiN2FlYzc1ZThhY2VhOGYyYzQxIiB9

QR-Code (frisch):
![2022-02-15_172256](https://user-images.githubusercontent.com/9672096/154105545-2fcc01d4-7450-478f-be84-a7d91db15f7f.png)

**Comment by ilya-smirnov-berlin** [comment]
Der Hash-Wert beim Testergebnis soll der gleiche sein, wie im QR-Code
(also im Beispiel oben dee72da76ce437713fc4a3f7fd04693a74dac923f829ab7aec75e8acea8f2c41 statt 891ea3d2cd72351af919b59ec428823507b67742addd08fd458ed01a3cf2aab2):

```
{
    "testResults":
    [
        {
            "id": "dee72da76ce437713fc4a3f7fd04693a74dac923f829ab7aec75e8acea8f2c41 ",
            "result": 6,
            "sc": 1644945777
        }
    ]
}
```

**Comment by WePo64** [comment]
Vielen Dank @ilya-smirnov-berlin 

Ich hatte den Satz aus der Anleitung "SHA256-Hashwert aus dem JSON-Objekt des QR-Codes"
falsch gelesen und einen SHA256-Hashwert von dem JSON-Objekt verwendet.
Deutsch 6 - setzen ;)

Danke

**Comment by bear-maaster** [comment]
Hi everyone!
I generated QR code and uploaded test result.
But I had a problem with https://dcc-proxy-cff4f7147260.coronawarn.app/version/v1/publicKey/search/{labId}.
It returns 403 error and nothing has changed yet.
And I 'd like someone to help me with my project.
Here is my skype id : live:.cid.dababe70c02930da
Thank you.
