### ISSUE TITLE
I 'd like someone to help me urgently.

### ISSUE THREAD

**Issue by bear-maaster** [corona-warn-app/cwa-quicktest-onboarding#92]
Hi everyone!
I generated QR code and uploaded test result.
But I had a problem with [https://dcc-proxy-cff4f7147260.coronawarn.app/version/v1/publicKey/search/{labId}](https://dcc-proxy-cff4f7147260.coronawarn.app/version/v1/publicKey/search/%7BlabId%7D).
It returns 403 error and nothing has changed yet.
And I 'd like someone to help me with my project.
Here is my skype id : live:.cid.dababe70c02930da
Thank you.

**Comment by ilya-smirnov-berlin** [comment]
Please contact us at [cwa-onboarding-schnittstelle@t-systems.com](mailto:cwa-onboarding-schnittstelle@t-systems.com) with more detailed information. Probably your access to DCC proxy need to be activated.
